### ISSUE TITLE
loading screen randomly interrupts gameplay

### ISSUE THREAD

**Issue by shole** [dharmab/a3tangohunt#21] opened 2014-11-01 21:24 UTC
here's some capture of this in action
http://youtu.be/x3eoknkAK9M
there's a few popups early on.. while viewing the map and a while later as i'm running
then there's a gap of maybe 4 minutes where it was smooth and i cut that bit out
then it starts appearing repeatedly
no mods are loaded

also, there are supposed to be more than just three bad guys, right?

**Comment by dharmab** [comment] 2016-01-16 16:58
Closing as I could not reproduce the issue.

**Closed by dharmab** 2016-01-16 16:58 UTC
